ignore:
  - "bienestar.cocina.back/src/main/java/org/bienestar/cocina/domain"  # ignore folders and all its contents
  # - "test_*.rb"       # wildcards accepted
  # - "**/*.py"         # glob accepted
  # - "[a-z]+/test_.*"  # regexp accepted